# Generated by Django 5.2.7 on 2025-10-27 14:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for the level', max_length=100)),
                ('code', models.CharField(help_text='Unique code for the level', max_length=50, unique=True)),
                ('type', models.CharField(choices=[('president', 'President'), ('course', 'Course Leader'), ('state', 'State Leader')], help_text='General category of the election level', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional description of the level')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, help_text='Specific course this level applies to', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('state', models.ForeignKey(blank=True, help_text='Specific state this level applies to', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.state')),
            ],
            options={
                'verbose_name': 'Election Level',
                'verbose_name_plural': 'Election Levels',
                'db_table': 'election_levels',
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the election', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the election')),
                ('start_date', models.DateTimeField(help_text='Date and time the election starts')),
                ('end_date', models.DateTimeField(help_text='Date and time the election ends')),
                ('is_active', models.BooleanField(default=False, help_text='Whether the election is currently active for voting')),
                ('has_ended', models.BooleanField(default=False, help_text='Whether the election has officially ended and results are final')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('levels', models.ManyToManyField(help_text='Election levels included in this election', related_name='elections', to='election.electionlevel')),
            ],
            options={
                'verbose_name': 'Election',
                'verbose_name_plural': 'Elections',
                'db_table': 'elections',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the position', max_length=100)),
                ('description', models.TextField(blank=True, help_text="Description of the position's responsibilities")),
                ('gender_restriction', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('any', 'Any')], default='any', help_text='Gender restriction for candidates (if any)', max_length=10)),
                ('election_level', models.ForeignKey(help_text='The election level this position belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='election.electionlevel')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'db_table': 'positions',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Biography or statement from the candidate')),
                ('platform', models.TextField(blank=True, help_text='Campaign platform or key points')),
                ('image', models.ImageField(blank=True, help_text='Profile image of the candidate', null=True, upload_to='candidate_images/')),
                ('vote_count', models.PositiveIntegerField(default=0, help_text='Cached count of votes received')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user who is the candidate', on_delete=django.db.models.deletion.CASCADE, related_name='candidacies', to=settings.AUTH_USER_MODEL)),
                ('election', models.ForeignKey(help_text='The election they are running in', on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='election.election')),
                ('position', models.ForeignKey(help_text='The specific position they are running for', on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='election.position')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'db_table': 'candidates',
            },
        ),
        migrations.CreateModel(
            name='VoterToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique token string', unique=True)),
                ('is_used', models.BooleanField(default=False, help_text='Whether this token has been used to cast a vote')),
                ('expiry_date', models.DateTimeField(help_text='Date and time the token expires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, help_text='Date and time the token was used', null=True)),
                ('election', models.ForeignKey(help_text='The election this token is for', on_delete=django.db.models.deletion.CASCADE, related_name='voter_tokens', to='election.election')),
                ('election_level', models.ForeignKey(help_text='The specific level within the election this token authorizes voting for', on_delete=django.db.models.deletion.CASCADE, related_name='voter_tokens', to='election.electionlevel')),
                ('user', models.ForeignKey(help_text='The user this token belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='voter_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voter Token',
                'verbose_name_plural': 'Voter Tokens',
                'db_table': 'voter_tokens',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Date and time the vote was cast')),
                ('candidate', models.ForeignKey(help_text='The candidate voted for', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='election.candidate')),
                ('election', models.ForeignKey(help_text='The election', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='election.election')),
                ('election_level', models.ForeignKey(help_text='The election level', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='election.electionlevel')),
                ('voter', models.ForeignKey(help_text='The user who voted', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
                ('token', models.ForeignKey(help_text='The token used to cast this vote', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='election.votertoken')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
                'db_table': 'votes',
            },
        ),
        migrations.AddIndex(
            model_name='electionlevel',
            index=models.Index(fields=['type'], name='election_le_type_29e554_idx'),
        ),
        migrations.AddIndex(
            model_name='electionlevel',
            index=models.Index(fields=['code'], name='election_le_code_4e1f4d_idx'),
        ),
        migrations.AddIndex(
            model_name='electionlevel',
            index=models.Index(fields=['course'], name='election_le_course__d77c5a_idx'),
        ),
        migrations.AddIndex(
            model_name='electionlevel',
            index=models.Index(fields=['state'], name='election_le_state_i_412196_idx'),
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['is_active'], name='elections_is_acti_1ae71f_idx'),
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['start_date'], name='elections_start_d_1e140f_idx'),
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['end_date'], name='elections_end_dat_dec9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['has_ended'], name='elections_has_end_4d2ca6_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['election_level'], name='positions_electio_ed7155_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('election_level', 'title', 'gender_restriction')},
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['election', 'position'], name='candidates_electio_728348_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['user'], name='candidates_user_id_5d06f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('user', 'election', 'position')},
        ),
        migrations.AddIndex(
            model_name='votertoken',
            index=models.Index(fields=['token'], name='voter_token_token_b5825a_idx'),
        ),
        migrations.AddIndex(
            model_name='votertoken',
            index=models.Index(fields=['election', 'election_level'], name='voter_token_electio_efd272_idx'),
        ),
        migrations.AddIndex(
            model_name='votertoken',
            index=models.Index(fields=['is_used'], name='voter_token_is_used_3b1752_idx'),
        ),
        migrations.AddIndex(
            model_name='votertoken',
            index=models.Index(fields=['expiry_date'], name='voter_token_expiry__b72f94_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='votertoken',
            unique_together={('user', 'election', 'election_level')},
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['token'], name='votes_token_i_f9f50e_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['candidate'], name='votes_candida_da1a33_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['election', 'election_level'], name='votes_electio_d151b1_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['timestamp'], name='votes_timesta_19f1d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('token',)},
        ),
    ]
