# Generated by Django 5.2.8 on 2025-11-14 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='running_mate',
            field=models.ForeignKey(blank=True, help_text='Running mate (e.g., Vice President candidate)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='running_mate_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidate',
            name='running_mate_bio',
            field=models.TextField(blank=True, help_text='Biography of the running mate'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='running_mate_image',
            field=models.ImageField(blank=True, help_text='Profile image of the running mate', null=True, upload_to='candidate_images/'),
        ),
    ]
