# Generated by Django 6.0.3 on 2026-03-29 17:45

from django.db import migrations
from django.utils import timezone
from datetime import timedelta
import random
import uuid


def create_test_users(apps, schema_editor):
    """Create 4 test users for public testing on landing page."""
    from django.contrib.auth.hashers import make_password
    
    User = apps.get_model('core', 'User')
    Course = apps.get_model('core', 'Course')
    State = apps.get_model('core', 'State')
    
    # Get BsCS course and states
    try:
        bscs_course = Course.objects.get(code='BsCS')
    except:
        print("⚠ BsCS course not found")
        return
    
    states = list(State.objects.all())
    
    test_users_data = [
        {
            'registration_number': 'T/TEST/2023/0001',
            'first_name': 'Test',
            'last_name': 'Voter',
            'email': 'test.voter@mwecau.ac.tz',
            'password': 'TestVoter@2024',
            'gender': 'male',
        },
        {
            'registration_number': 'T/TEST/2023/0002',
            'first_name': 'Demo',
            'last_name': 'Student',
            'email': 'demo.student@mwecau.ac.tz',
            'password': 'DemoStudent@2024',
            'gender': 'female',
        },
        {
            'registration_number': 'T/TEST/2023/0003',
            'first_name': 'Sample',
            'last_name': 'User',
            'email': 'sample.user@mwecau.ac.tz',
            'password': 'SampleUser@2024',
            'gender': 'male',
        },
        {
            'registration_number': 'T/TEST/2023/0004',
            'first_name': 'Public',
            'last_name': 'Tester',
            'email': 'public.tester@mwecau.ac.tz',
            'password': 'PublicTest@2024',
            'gender': 'female',
        },
    ]
    
    created_users = []
    for data in test_users_data:
        password = data.pop('password')
        user, created = User.objects.get_or_create(
            registration_number=data['registration_number'],
            defaults={
                **data,
                'password': make_password(password),
                'course': bscs_course,
                'state': random.choice(states) if states else None,
                'voter_id': str(uuid.uuid4()),
                'is_verified': True,
                'date_verified': timezone.now(),
                'role': 'voter',
            }
        )
        if created:
            created_users.append(user)
    
    print(f"✓ Created {len(created_users)} test users")
    return created_users


def create_users_from_college_data(apps, schema_editor):
    """Convert some CollegeData entries to User accounts."""
    from django.contrib.auth.hashers import make_password
    
    User = apps.get_model('core', 'User')
    CollegeData = apps.get_model('core', 'CollegeData')
    State = apps.get_model('core', 'State')
    
    states = list(State.objects.all())
    
    # Get 20 random unused college data entries
    college_data_entries = list(CollegeData.objects.filter(is_used=False)[:20])
    
    created_users = []
    for data in college_data_entries:
        # Infer gender from first name (basic heuristic)
        first_name_upper = data.first_name.upper()
        gender = 'female' if any(name in first_name_upper for name in ['SESILIA', 'WEMA', 'AMINA', 'CHRISTINA', 'JOYCE', 'MARWA', 'ANETH']) else 'male'
        
        user, created = User.objects.get_or_create(
            registration_number=data.registration_number,
            defaults={
                'first_name': data.first_name,
                'last_name': data.last_name,
                'email': data.email if data.email else f"{data.registration_number.lower().replace('/', '.')}@student.mwecau.ac.tz",
                'password': make_password('DefaultPass@2024'),
                'course': data.course,
                'state': random.choice(states) if states else None,
                'gender': gender,
                'voter_id': str(uuid.uuid4()),
                'is_verified': True,
                'date_verified': timezone.now(),
                'role': 'voter',
            }
        )
        if created:
            data.is_used = True
            data.status = 'processed'
            data.save()
            created_users.append(user)
    
    print(f"✓ Created {len(created_users)} users from CollegeData")
    return created_users


def create_election_structure(apps, schema_editor):
    """Create election levels, positions, and election."""
    ElectionLevel = apps.get_model('election', 'ElectionLevel')
    Position = apps.get_model('election', 'Position')
    Election = apps.get_model('election', 'Election')
    Course = apps.get_model('core', 'Course')
    State = apps.get_model('core', 'State')
    
    # Get BsCS course
    try:
        bscs_course = Course.objects.get(code='BsCS')
    except:
        print("⚠ BsCS course not found")
        return None, []
    
    states = list(State.objects.all())
    
    # Create Election Levels
    levels = []
    
    # 1. President Level
    president_level, _ = ElectionLevel.objects.get_or_create(
        code='PRESIDENT_2024',
        defaults={
            'name': 'University President',
            'type': 'president',
            'description': 'University-wide presidential election',
        }
    )
    levels.append(president_level)
    
    # 2. Course Leader Level (BsCS)
    course_level, _ = ElectionLevel.objects.get_or_create(
        code='COURSE_BSCS_2024',
        defaults={
            'name': 'BsCS Course Leader',
            'type': 'course',
            'course': bscs_course,
            'description': 'Course representative for Computer Science students',
        }
    )
    levels.append(course_level)
    
    # 3. State Leaders (for each state)
    for state in states:
        state_code = state.name.replace(' ', '_').upper()
        state_level, _ = ElectionLevel.objects.get_or_create(
            code=f'STATE_{state_code}_2024',
            defaults={
                'name': f'{state.name} State Leader',
                'type': 'state',
                'state': state,
                'description': f'Representative for {state.name} residents',
            }
        )
        levels.append(state_level)
    
    print(f"✓ Created {len(levels)} election levels")
    
    # Create Positions
    positions = []
    
    # President positions (President & Vice President)
    pres_pos, _ = Position.objects.get_or_create(
        election_level=president_level,
        title='President',
        gender_restriction='any',
        defaults={'description': 'University Student President'}
    )
    positions.append(pres_pos)
    
    vice_pres_pos, _ = Position.objects.get_or_create(
        election_level=president_level,
        title='Vice President',
        gender_restriction='any',
        defaults={'description': 'University Student Vice President'}
    )
    positions.append(vice_pres_pos)
    
    # Course leader position
    course_pos, _ = Position.objects.get_or_create(
        election_level=course_level,
        title='Course Representative',
        gender_restriction='any',
        defaults={'description': 'BsCS Course Representative'}
    )
    positions.append(course_pos)
    
    # State leader positions
    for state in states:
        state_code = state.name.replace(' ', '_').upper()
        state_level = ElectionLevel.objects.get(code=f'STATE_{state_code}_2024')
        
        state_pos, _ = Position.objects.get_or_create(
            election_level=state_level,
            title='State Representative',
            gender_restriction='any',
            defaults={'description': f'{state.name} Representative'}
        )
        positions.append(state_pos)
    
    print(f"✓ Created {len(positions)} positions")
    
    # Create Election
    start_date = timezone.now() + timedelta(days=1)
    end_date = start_date + timedelta(days=7)
    
    election, created = Election.objects.get_or_create(
        title='MWECAU General Elections 2024',
        defaults={
            'description': 'General student elections for university president, course leaders, and state representatives.',
            'start_date': start_date,
            'end_date': end_date,
            'is_active': False,
            'has_ended': False,
        }
    )
    
    if created:
        election.levels.set(levels)
        print(f"✓ Created election: {election.title}")
    
    return election, positions


def create_candidates(apps, schema_editor):
    """Create random candidates for all positions."""
    User = apps.get_model('core', 'User')
    Election = apps.get_model('election', 'Election')
    Position = apps.get_model('election', 'Position')
    Candidate = apps.get_model('election', 'Candidate')
    
    try:
        election = Election.objects.get(title='MWECAU General Elections 2024')
    except:
        print("⚠ Election not found")
        return
    
    # Get all verified users
    all_users = list(User.objects.filter(is_verified=True))
    
    if len(all_users) < 5:
        print(f"⚠ Not enough users ({len(all_users)}) to create candidates")
        return
    
    positions = Position.objects.all()
    created_candidates = []
    
    for position in positions:
        # Determine eligible users for this position
        eligible_users = []
        
        if position.election_level.type == 'president':
            # Anyone can run for president
            eligible_users = all_users
        elif position.election_level.type == 'course':
            # Must be in the specific course
            eligible_users = [u for u in all_users if u.course_id == position.election_level.course_id]
        elif position.election_level.type == 'state':
            # Must be in the specific state
            eligible_users = [u for u in all_users if u.state_id == position.election_level.state_id]
        
        # Filter by gender restriction
        if position.gender_restriction != 'any':
            eligible_users = [u for u in eligible_users if u.gender == position.gender_restriction]
        
        # Randomly select 2-3 candidates for this position
        num_candidates = min(random.randint(2, 3), len(eligible_users))
        
        if num_candidates == 0:
            continue
        
        selected_users = random.sample(eligible_users, num_candidates)
        
        for user in selected_users:
            # Check if already candidate in this election
            if Candidate.objects.filter(user=user, election=election).exists():
                continue
            
            candidate, created = Candidate.objects.get_or_create(
                user=user,
                election=election,
                position=position,
                defaults={
                    'bio': f'I am {user.first_name} {user.last_name}, running for {position.title}.',
                    'platform': f'Vote for change! Vote for {user.first_name}!',
                    'vote_count': 0,
                }
            )
            
            if created:
                created_candidates.append(candidate)
    
    print(f"✓ Created {len(created_candidates)} candidates across all positions")


def seed_election_data(apps, schema_editor):
    """Main function to seed all election data."""
    print("\n" + "="*60)
    print("SEEDING ELECTION DATA")
    print("="*60 + "\n")
    
    # Step 1: Create test users
    print("1. Creating test users...")
    create_test_users(apps, schema_editor)
    
    # Step 2: Convert CollegeData to Users
    print("\n2. Converting CollegeData to Users...")
    create_users_from_college_data(apps, schema_editor)
    
    # Step 3: Create election structure
    print("\n3. Creating election structure...")
    create_election_structure(apps, schema_editor)
    
    # Step 4: Create candidates
    print("\n4. Creating candidates...")
    create_candidates(apps, schema_editor)
    
    print("\n" + "="*60)
    print("ELECTION DATA SEEDING COMPLETE")
    print("="*60 + "\n")


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
        ('core', '0004_cleanup_duplicate_states'),
    ]

    operations = [
        migrations.RunPython(seed_election_data, reverse_code=migrations.RunPython.noop),
    ]
