# Generated by Django 6.0.3 on 2026-05-01 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_vote_voter_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vote',
            name='votes_voter_idx',
        ),
        migrations.RemoveIndex(
            model_name='vote',
            name='votes_voter_election_idx',
        ),
    ]
