# Generated by Django 5.2.5 on 2025-08-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['token', 'candidate'], name='election_vo_token_i_2ae447_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['candidate', 'timestamp'], name='election_vo_candida_803f21_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['election'], name='election_vo_electio_f3c178_idx'),
        ),
    ]
