# Generated by Django 5.2.7 on 2025-10-23 08:16

import core.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='courses_code_fa42f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'states',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='states_name_9db832_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('registration_number', models.CharField(help_text='University registration number (e.g., T/XXX/202X/XXX)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Registration number must contain only uppercase letters, numbers, or slashes.', regex='^[A-Z0-9/]+$')])),
                ('email', models.EmailField(blank=True, help_text='Required email for notifications and password resets', max_length=254, null=True, unique=True, verbose_name='email address')),
                ('voter_id', models.CharField(blank=True, help_text='Unique voter ID for anonymous voting, auto-generated UUID', max_length=36, null=True, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text="User's gender for position eligibility", max_length=10, null=True)),
                ('role', models.CharField(choices=[('voter', 'Voter'), ('candidate', 'Candidate'), ('class_leader', 'Class Leader'), ('commissioner', 'Commissioner')], default='voter', help_text="User's role in the election system", max_length=20)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the user account is verified')),
                ('date_verified', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('course', models.ForeignKey(blank=True, help_text="User's academic course", null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.course')),
                ('state', models.ForeignKey(blank=True, help_text="User's state/region", null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.state')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CollegeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Registration number must contain only uppercase letters, numbers, or slashes.', regex='^[A-Z0-9/]+$')])),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, help_text='Required email for user account creation', max_length=254)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Gender of the student', max_length=10, null=True)),
                ('voter_id', models.CharField(blank=True, help_text='Unique voter ID for anonymous voting, auto-generated UUID', max_length=36, null=True, unique=True)),
                ('is_used', models.BooleanField(default=False, help_text='Whether this data has been used to create a user account')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', help_text='Processing status for async tasks', max_length=20)),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='Class leader or commissioner who uploaded this data', limit_choices_to={'role__in': ['class_leader', 'commissioner']}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
            ],
            options={
                'verbose_name': 'College Data',
                'verbose_name_plural': 'College Data',
                'db_table': 'college_data',
                'indexes': [models.Index(fields=['registration_number'], name='college_dat_registr_86e753_idx'), models.Index(fields=['course', 'is_used'], name='college_dat_course__1baf12_idx'), models.Index(fields=['status'], name='college_dat_status_24a8f1_idx'), models.Index(fields=['voter_id'], name='college_dat_voter_i_fbb903_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['registration_number'], name='users_registr_4b432d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_verified'], name='users_role_a93a92_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['state', 'course'], name='users_state_i_e49108_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['gender'], name='users_gender_c12881_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['voter_id'], name='users_voter_i_c1d34a_idx'),
        ),
    ]
