# Generated by Django 6.0.3 on 2026-03-29 17:40

from django.db import migrations
import csv
import os


def load_states(apps, schema_editor):
    """Load states from CSV or predefined list."""
    State = apps.get_model('core', 'State')
    
    states_data = [
        'KIFUMBU',
        'MAWELA',
        'KWACHANGE',
        'WHITE HOUSE',
        'MOSHI MJINI',
        'ON-CAMPUS',
    ]
    
    for state_name in states_data:
        State.objects.get_or_create(name=state_name)
    
    print(f"✓ Loaded {len(states_data)} states")


def load_courses(apps, schema_editor):
    """Load courses from CSV file."""
    Course = apps.get_model('core', 'Course')
    
    # Path to CSV file
    csv_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__)))),
        'data', 'courses_mwecau.csv'
    )
    
    created_count = 0
    if os.path.exists(csv_path):
        with open(csv_path, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                _, created = Course.objects.get_or_create(
                    code=row['code'],
                    defaults={'name': row['name']}
                )
                if created:
                    created_count += 1
        print(f"✓ Loaded {created_count} courses from CSV")
    else:
        # Fallback: Create BsCS course if CSV not found
        Course.objects.get_or_create(
            code='BsCS',
            defaults={'name': 'Bachelor of Science in Computer Science'}
        )
        print("✓ Created default BsCS course")


def load_students_as_college_data(apps, schema_editor):
    """Load students from CSV as CollegeData entries."""
    CollegeData = apps.get_model('core', 'CollegeData')
    Course = apps.get_model('core', 'Course')
    
    # Path to CSV file
    csv_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__)))),
        'data', 'csc_students_sample.csv'
    )
    
    created_count = 0
    if os.path.exists(csv_path):
        with open(csv_path, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                # Get the course
                try:
                    course = Course.objects.get(code=row['course_code'])
                except Course.DoesNotExist:
                    print(f"⚠ Course {row['course_code']} not found, skipping {row['registration_number']}")
                    continue
                
                # Parse name (assuming format: "FIRST MIDDLE LAST" or "FIRST LAST")
                name_parts = row['name'].strip().split()
                if len(name_parts) >= 2:
                    first_name = name_parts[0]
                    last_name = ' '.join(name_parts[1:])
                else:
                    first_name = row['name']
                    last_name = ''
                
                # Create CollegeData entry
                _, created = CollegeData.objects.get_or_create(
                    registration_number=row['registration_number'],
                    defaults={
                        'first_name': first_name,
                        'last_name': last_name,
                        'course': course,
                        'status': 'pending',
                        'is_used': False,
                    }
                )
                if created:
                    created_count += 1
        
        print(f"✓ Loaded {created_count} students as CollegeData")
    else:
        print("⚠ Student CSV not found at:", csv_path)


def reverse_data(apps, schema_editor):
    """Remove seeded data when rolling back migration."""
    State = apps.get_model('core', 'State')
    Course = apps.get_model('core', 'Course')
    CollegeData = apps.get_model('core', 'CollegeData')
    
    # Only delete if they haven't been used
    CollegeData.objects.filter(is_used=False).delete()
    print("✓ Removed unused CollegeData entries")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_registration_number'),
    ]

    operations = [
        migrations.RunPython(load_states, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(load_courses, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(load_students_as_college_data, reverse_code=reverse_data),
    ]
