# Generated by Django 6.0.3 on 2026-03-29 17:41

from django.db import migrations


def cleanup_duplicate_states(apps, schema_editor):
    """Remove duplicate states and standardize naming."""
    State = apps.get_model('core', 'State')
    User = apps.get_model('core', 'User')
    
    # Define the canonical states
    canonical_states = {
        'KIFUMBU': ['Kifumbu', 'kifumbu'],
        'MAWELA': ['Mawela', 'mawela'],
        'KWACHANGE': ['Change', 'change', 'Kwachange', 'kwachange'],
        'WHITE HOUSE': ['White House', 'white house', 'Whitehouse', 'whitehouse'],
        'MOSHI MJINI': ['Moshi Mjini', 'moshi mjini', 'Moshi'],
        'ON-CAMPUS': ['On-Campus', 'on-campus', 'On Campus', 'Campus'],
    }
    
    for canonical_name, variations in canonical_states.items():
        # Get or create the canonical state
        canonical_state, _ = State.objects.get_or_create(name=canonical_name)
        
        # Find all variations
        for variation in variations:
            duplicate_states = State.objects.filter(name=variation).exclude(id=canonical_state.id)
            
            for duplicate in duplicate_states:
                # Update all users pointing to this duplicate
                User.objects.filter(state=duplicate).update(state=canonical_state)
                
                # Delete the duplicate
                duplicate.delete()
                print(f"  Merged '{variation}' into '{canonical_name}'")
    
    print(f"✓ Cleaned up duplicate states. Total states: {State.objects.count()}")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_initial_data'),
    ]

    operations = [
        migrations.RunPython(cleanup_duplicate_states, reverse_code=migrations.RunPython.noop),
    ]
