# Generated by Django 6.0.3 on 2026-05-01 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cleanup_duplicate_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_number',
            field=models.CharField(help_text='University registration number (e.g., T/XXX/20XX/XXX)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Registration number must contain only uppercase letters, numbers, or slashes.', regex='^[A-Z0-9/]+$')]),
        ),
    ]
