# Generated by Django 6.0.3 on 2026-05-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Required email for notifications and password resets', max_length=254, null=True, verbose_name='email address'),
        ),
    ]
