# Generated by Django 5.2.5 on 2025-08-25 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_number',
            field=models.CharField(help_text='University registration number (e.g., T/XXX/202X/XXX)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Registration number must contain only uppercase letters, numbers, or slashes.', regex='^[A-Z0-9/]+$')]),
        ),
    ]
