# Generated by Django 5.2.5 on 2025-08-26 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_registration_number'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='course',
            new_name='courses_code_fa42f1_idx',
            old_name='course_code_83d7d9_idx',
        ),
        migrations.RenameIndex(
            model_name='state',
            new_name='states_name_9db832_idx',
            old_name='state_majim_name_285bbd_idx',
        ),
        migrations.AlterModelTable(
            name='course',
            table='courses',
        ),
        migrations.AlterModelTable(
            name='state',
            table='states',
        ),
    ]
