# Generated by Django 5.2.5 on 2025-08-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Required email for notifications and password resets', max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
