# Generated by Django 5.2.5 on 2025-08-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Required email for notifications and password resets', max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
