# Generated by Django 5.2.5 on 2025-08-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_collegedata_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegedata',
            name='email',
            field=models.EmailField(blank=True, help_text='Required email for user account creation', max_length=254),
        ),
    ]
