# Generated by Django 5.2.5 on 2025-09-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_collegedata_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegedata',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Gender of the student', max_length=10, null=True),
        ),
    ]
